# Generated by Django 2.2.6 on 2019-10-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64, verbose_name='Descripcion')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('abreviacion', models.CharField(max_length=4, verbose_name='Abreviacion')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha Valoracion')),
                ('valoracion', models.PositiveIntegerField(verbose_name='Valoracion')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('porciones', models.PositiveIntegerField(verbose_name='Cantidad de porciones')),
                ('ingredientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Ingredientes')),
                ('pasos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Pasos')),
                ('valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Valoracion')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Unidades'),
        ),
    ]
