# Generated by Django 2.2.6 on 2019-10-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='pasos',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='valoracion',
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Receta'),
        ),
        migrations.AddField(
            model_name='pasos',
            name='receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Receta'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Receta'),
        ),
    ]
