# Generated by Django 2.2.6 on 2019-10-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191009_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='receta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='main_app.Receta'),
        ),
    ]
